//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prekenweb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prekenweb.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by.
        /// </summary>
        public static string AangemaaktDoor {
            get {
                return ResourceManager.GetString("AangemaaktDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string AangemaaktOp {
            get {
                return ResourceManager.GetString("AangemaaktOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string AangepastDoor {
            get {
                return ResourceManager.GetString("AangepastDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/sing.
        /// </summary>
        public static string AankondigingenBord {
            get {
                return ResourceManager.GetString("AankondigingenBord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be translated.
        /// </summary>
        public static string AankondigingenBordTooltip {
            get {
                return ResourceManager.GetString("AankondigingenBordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Aanmaken {
            get {
                return ResourceManager.GetString("Aanmaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times visited.
        /// </summary>
        public static string AantalKeerGedownload {
            get {
                return ResourceManager.GetString("AantalKeerGedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailings.
        /// </summary>
        public static string AantalMailings {
            get {
                return ResourceManager.GetString("AantalMailings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AantalRollen {
            get {
                return ResourceManager.GetString("AantalRollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement.
        /// </summary>
        public static string Aanvulling {
            get {
                return ResourceManager.GetString("Aanvulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement is required.
        /// </summary>
        public static string AanvullingIsVerplicht {
            get {
                return ResourceManager.GetString("AanvullingIsVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Afbeeldingen {
            get {
                return ResourceManager.GetString("Afbeeldingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Afdrukken {
            get {
                return ResourceManager.GetString("Afdrukken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string Afdrukweergave {
            get {
                return ResourceManager.GetString("Afdrukweergave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Afgehandeld {
            get {
                return ResourceManager.GetString("Afgehandeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Afspelen {
            get {
                return ResourceManager.GetString("Afspelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string AfspelenKop {
            get {
                return ResourceManager.GetString("AfspelenKop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Afzender {
            get {
                return ResourceManager.GetString("Afzender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Algemeen {
            get {
                return ResourceManager.GetString("Algemeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Alle {
            get {
                return ResourceManager.GetString("Alle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only admins.
        /// </summary>
        public static string AlleenBeheerders {
            get {
                return ResourceManager.GetString("AlleenBeheerders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sermons have been published.
        /// </summary>
        public static string AllLecturesHaveBeenPublished {
            get {
                return ResourceManager.GetString("AllLecturesHaveBeenPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio sermon.
        /// </summary>
        public static string AudioPreek {
            get {
                return ResourceManager.GetString("AudioPreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatisch {
            get {
                return ResourceManager.GetString("Automatisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibletext generation.
        /// </summary>
        public static string AutomatischeTeksten {
            get {
                return ResourceManager.GetString("AutomatischeTeksten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen this lecture.
        /// </summary>
        public static string BeluisterDezeLezing {
            get {
                return ResourceManager.GetString("BeluisterDezeLezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen this sermon.
        /// </summary>
        public static string BeluisterDezePreek {
            get {
                return ResourceManager.GetString("BeluisterDezePreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Bestand {
            get {
                return ResourceManager.GetString("Bestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filemanager.
        /// </summary>
        public static string Bestandsbeheer {
            get {
                return ResourceManager.GetString("Bestandsbeheer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Bewerk {
            get {
                return ResourceManager.GetString("Bewerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this sermon.
        /// </summary>
        public static string BewerkDezePreek {
            get {
                return ResourceManager.GetString("BewerkDezePreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sermon.
        /// </summary>
        public static string BewerkPreek {
            get {
                return ResourceManager.GetString("BewerkPreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible book.
        /// </summary>
        public static string Bijbelboek {
            get {
                return ResourceManager.GetString("Bijbelboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible books.
        /// </summary>
        public static string BijbelBoeken {
            get {
                return ResourceManager.GetString("BijbelBoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible part.
        /// </summary>
        public static string Bijbelgedeelte {
            get {
                return ResourceManager.GetString("Bijbelgedeelte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible text description.
        /// </summary>
        public static string BijbeltekstOmschrijving {
            get {
                return ResourceManager.GetString("BijbeltekstOmschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        public static string Bijdragen {
            get {
                return ResourceManager.GetString("Bijdragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string BijgewerktOp {
            get {
                return ResourceManager.GetString("BijgewerktOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Bladeren {
            get {
                return ResourceManager.GetString("Bladeren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark placed at {0:dd-MM-yyyy hh:mm}, click here to remove bookbark.
        /// </summary>
        public static string BladwijzerAlGelegd {
            get {
                return ResourceManager.GetString("BladwijzerAlGelegd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarked at {0:g}, click here to remove bookmark.
        /// </summary>
        public static string BladwijzerGeplaatstOp {
            get {
                return ResourceManager.GetString("BladwijzerGeplaatstOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark this sermon.
        /// </summary>
        public static string BladwijzerLeggen {
            get {
                return ResourceManager.GetString("BladwijzerLeggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to bookmark this sermon.
        /// </summary>
        public static string BladwijzerPlaatsen {
            get {
                return ResourceManager.GetString("BladwijzerPlaatsen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add this sermon to your personal list of bookmarked sermons.
        /// </summary>
        public static string BladwijzerTooltip {
            get {
                return ResourceManager.GetString("BladwijzerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Boek {
            get {
                return ResourceManager.GetString("Boek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is not valid.
        /// </summary>
        public static string CaptchaOngeldig {
            get {
                return ResourceManager.GetString("CaptchaOngeldig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here the text as in the image above.
        /// </summary>
        public static string CaptchaOvertypen {
            get {
                return ResourceManager.GetString("CaptchaOvertypen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactKop {
            get {
                return ResourceManager.GetString("ContactKop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue where you left off?.
        /// </summary>
        public static string ContinueWhereLeftOff {
            get {
                return ResourceManager.GetString("ContinueWhereLeftOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create event.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation date of this sermon: {0:yyyy/MM/dd}.
        /// </summary>
        public static string DatumPreekAangemaaktTooltip {
            get {
                return ResourceManager.GetString("DatumPreekAangemaaktTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date on which this sermon has been published: {0:dd-MM-yyyy}.
        /// </summary>
        public static string DatumPreekGepubliceerdTooltip {
            get {
                return ResourceManager.GetString("DatumPreekGepubliceerdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time.
        /// </summary>
        public static string DatumTijd {
            get {
                return ResourceManager.GetString("DatumTijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook.
        /// </summary>
        public static string DeelOpFacebook {
            get {
                return ResourceManager.GetString("DeelOpFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on LinkedIn.
        /// </summary>
        public static string DeelOpLinkedIn {
            get {
                return ResourceManager.GetString("DeelOpLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Twitter.
        /// </summary>
        public static string DeelOpTwitter {
            get {
                return ResourceManager.GetString("DeelOpTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via e-mail.
        /// </summary>
        public static string DeelViaMail {
            get {
                return ResourceManager.GetString("DeelViaMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Delen {
            get {
                return ResourceManager.GetString("Delen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dutch Confession.
        /// </summary>
        public static string DeNederlandseGeloofsbelijdenis {
            get {
                return ResourceManager.GetString("DeNederlandseGeloofsbelijdenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent visited sermons.
        /// </summary>
        public static string DoorMijBeluisterd {
            get {
                return ResourceManager.GetString("DoorMijBeluisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canons.
        /// </summary>
        public static string DordtseLeerregels {
            get {
                return ResourceManager.GetString("DordtseLeerregels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sermon.
        /// </summary>
        public static string DownloadPreek {
            get {
                return ResourceManager.GetString("DownloadPreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as Epub.
        /// </summary>
        public static string DownloadPreekAlsEpub {
            get {
                return ResourceManager.GetString("DownloadPreekAlsEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sermon as PDF.
        /// </summary>
        public static string DownloadPreekAlsPDF {
            get {
                return ResourceManager.GetString("DownloadPreekAlsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download sermon as MS Word.
        /// </summary>
        public static string DownloadPreekAlsWord {
            get {
                return ResourceManager.GetString("DownloadPreekAlsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is required.
        /// </summary>
        public static string EmailIsVerplicht {
            get {
                return ResourceManager.GetString("EmailIsVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already taken, try &lt;a href=&apos;{0}&apos;&gt;forgot password&lt;/a&gt;.
        /// </summary>
        public static string EmailNietBeschikbaar {
            get {
                return ResourceManager.GetString("EmailNietBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not yet confirmed.
        /// </summary>
        public static string EmailOnbevestigd {
            get {
                return ResourceManager.GetString("EmailOnbevestigd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Engels {
            get {
                return ResourceManager.GetString("Engels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string EventSorting {
            get {
                return ResourceManager.GetString("EventSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a login, please try again.
        /// </summary>
        public static string ExterneLoginFout {
            get {
                return ResourceManager.GetString("ExterneLoginFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SermonWeb.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string FinancieleBijdrage {
            get {
                return ResourceManager.GetString("FinancieleBijdrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Geavanceerd {
            get {
                return ResourceManager.GetString("Geavanceerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Gebeurtenis {
            get {
                return ResourceManager.GetString("Gebeurtenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Gebeurtenissen {
            get {
                return ResourceManager.GetString("Gebeurtenissen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already registred.
        /// </summary>
        public static string GebruikerIsAlGeregistreerd {
            get {
                return ResourceManager.GetString("GebruikerIsAlGeregistreerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Gebruikers {
            get {
                return ResourceManager.GetString("Gebruikers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Gebruikersnaam {
            get {
                return ResourceManager.GetString("Gebruikersnaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email unkown.
        /// </summary>
        public static string GebruikersnaamEmailOnbekend {
            get {
                return ResourceManager.GetString("GebruikersnaamEmailOnbekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not available.
        /// </summary>
        public static string GebruikersnaamNietBeschikbaar {
            get {
                return ResourceManager.GetString("GebruikersnaamNietBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string GebruikersnaamVerplicht {
            get {
                return ResourceManager.GetString("GebruikersnaamVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area on site.
        /// </summary>
        public static string Gedeelte {
            get {
                return ResourceManager.GetString("Gedeelte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results....
        /// </summary>
        public static string GeenResultaten {
            get {
                return ResourceManager.GetString("GeenResultaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve data.
        /// </summary>
        public static string GegevensAanvullen {
            get {
                return ResourceManager.GetString("GegevensAanvullen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Gelegenheden {
            get {
                return ResourceManager.GetString("Gelegenheden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregation.
        /// </summary>
        public static string Gemeente {
            get {
                return ResourceManager.GetString("Gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregations.
        /// </summary>
        public static string Gemeentes {
            get {
                return ResourceManager.GetString("Gemeentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preached.
        /// </summary>
        public static string GepreektOp {
            get {
                return ResourceManager.GetString("GepreektOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Gepubliceerd {
            get {
                return ResourceManager.GetString("Gepubliceerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published on.
        /// </summary>
        public static string GepubliceerdOp {
            get {
                return ResourceManager.GetString("GepubliceerdOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Handmatig {
            get {
                return ResourceManager.GetString("Handmatig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heidelberg Catechism.
        /// </summary>
        public static string HeidelbergseCatechismus {
            get {
                return ResourceManager.GetString("HeidelbergseCatechismus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeKop {
            get {
                return ResourceManager.GetString("HomeKop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string Hoofdstuk {
            get {
                return ResourceManager.GetString("Hoofdstuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string HuidigWachtwoord {
            get {
                return ResourceManager.GetString("HuidigWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea.
        /// </summary>
        public static string Idee {
            get {
                return ResourceManager.GetString("Idee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Inloggen {
            get {
                return ResourceManager.GetString("Inloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is possible to take personal notes on a sermon but you need to be logged in..
        /// </summary>
        public static string InlogRedenAantekeningen {
            get {
                return ResourceManager.GetString("InlogRedenAantekeningen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When logged in you can place a bookmark on a sermon. Because this functionality is personal you need to be logged in on SermonWeb.org.
        /// </summary>
        public static string InlogRedenBladwijzer {
            get {
                return ResourceManager.GetString("InlogRedenBladwijzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SermonWeb can resume a sermon from where you left it when you&apos;re logged in.
        /// </summary>
        public static string InlogRedenPreekVerderAfluisteren {
            get {
                return ResourceManager.GetString("InlogRedenPreekVerderAfluisteren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged in to create your own Rss feed based on a search query!.
        /// </summary>
        public static string InlogRedenRssFeed {
            get {
                return ResourceManager.GetString("InlogRedenRssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re logged in you can save you&apos;re search queries.
        /// </summary>
        public static string InlogRedenZoekOpdrachtBewaren {
            get {
                return ResourceManager.GetString("InlogRedenZoekOpdrachtBewaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Inschrijven {
            get {
                return ResourceManager.GetString("Inschrijven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string InschrijvenNieuwsbrief {
            get {
                return ResourceManager.GetString("InschrijvenNieuwsbrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string InschrijvenNieuwsbriefKnop {
            get {
                return ResourceManager.GetString("InschrijvenNieuwsbriefKnop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructionvideo.
        /// </summary>
        public static string Instructievideo {
            get {
                return ResourceManager.GetString("Instructievideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using a iOS device, it is not possible to download and save sermons on your device. Click OK to proceed listen/stream this sermon, a persistent internet connection is required..
        /// </summary>
        public static string iOSDownloadBevestiging {
            get {
                return ResourceManager.GetString("iOSDownloadBevestiging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Ja {
            get {
                return ResourceManager.GetString("Ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Kies {
            get {
                return ResourceManager.GetString("Kies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within lectures the following categories are known:.
        /// </summary>
        public static string KnownLectureCategories {
            get {
                return ResourceManager.GetString("KnownLectureCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Laatste {
            get {
                return ResourceManager.GetString("Laatste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last visit.
        /// </summary>
        public static string LaatsteBezoek {
            get {
                return ResourceManager.GetString("LaatsteBezoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last signin.
        /// </summary>
        public static string LaatstIngelogd {
            get {
                return ResourceManager.GetString("LaatstIngelogd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Lees {
            get {
                return ResourceManager.GetString("Lees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read this sermon.
        /// </summary>
        public static string LeesDezePreek {
            get {
                return ResourceManager.GetString("LeesDezePreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and reading sermons.
        /// </summary>
        public static string LeesEnAudioPreken {
            get {
                return ResourceManager.GetString("LeesEnAudioPreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string LeesPreek {
            get {
                return ResourceManager.GetString("LeesPreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading text.
        /// </summary>
        public static string LeesPreekTekst {
            get {
                return ResourceManager.GetString("LeesPreekTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can paste the reading sermon text from Microsoft Word.
        /// </summary>
        public static string LeesPreekTekstTooltip {
            get {
                return ResourceManager.GetString("LeesPreekTekstTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sermons.
        /// </summary>
        public static string Leespreken {
            get {
                return ResourceManager.GetString("Leespreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Sermons and Lectures.
        /// </summary>
        public static string LeesprekenEnLezingen {
            get {
                return ResourceManager.GetString("LeesprekenEnLezingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifespan.
        /// </summary>
        public static string Levensperiode {
            get {
                return ResourceManager.GetString("Levensperiode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Lezen {
            get {
                return ResourceManager.GetString("Lezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Lezing {
            get {
                return ResourceManager.GetString("Lezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture category.
        /// </summary>
        public static string LezingCategorie {
            get {
                return ResourceManager.GetString("LezingCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        public static string Lezingen {
            get {
                return ResourceManager.GetString("Lezingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Sermons and Lectures.
        /// </summary>
        public static string LezingenEnAudioPreken {
            get {
                return ResourceManager.GetString("LezingenEnAudioPreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture description.
        /// </summary>
        public static string LezingOmschrijving {
            get {
                return ResourceManager.GetString("LezingOmschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I you don&apos;t have a social login, login using your SermonWeb.org account.
        /// </summary>
        public static string LoginHeeftUGeenSocial {
            get {
                return ResourceManager.GetString("LoginHeeftUGeenSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using Facebook or Twitter so you dont need a SermonWeb.org account.
        /// </summary>
        public static string LoginSocial {
            get {
                return ResourceManager.GetString("LoginSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using.
        /// </summary>
        public static string LoginVia {
            get {
                return ResourceManager.GetString("LoginVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U bent succesvol uitgelogd!.
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Luister {
            get {
                return ResourceManager.GetString("Luister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string Meer {
            get {
                return ResourceManager.GetString("Meer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More sermons about this event.
        /// </summary>
        public static string MeerPrekenGelegenheid {
            get {
                return ResourceManager.GetString("MeerPrekenGelegenheid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More sermons in this series.
        /// </summary>
        public static string MeerUitDezeSerie {
            get {
                return ResourceManager.GetString("MeerUitDezeSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More of this book.
        /// </summary>
        public static string MeerUitDitBoek {
            get {
                return ResourceManager.GetString("MeerUitDitBoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More sermons of this minister.
        /// </summary>
        public static string MeerVanDezePredikant {
            get {
                return ResourceManager.GetString("MeerVanDezePredikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string MenuBeheer {
            get {
                return ResourceManager.GetString("MenuBeheer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string MenuBoeken {
            get {
                return ResourceManager.GetString("MenuBoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string MenuHulp {
            get {
                return ResourceManager.GetString("MenuHulp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string MenuLinks {
            get {
                return ResourceManager.GetString("MenuLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons with bookmark.
        /// </summary>
        public static string MetBladwijzer {
            get {
                return ResourceManager.GetString("MetBladwijzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MijnGegevens {
            get {
                return ResourceManager.GetString("MijnGegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My SermonWeb.org.
        /// </summary>
        public static string MijnPrekenweb {
            get {
                return ResourceManager.GetString("MijnPrekenweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Naam {
            get {
                return ResourceManager.GetString("Naam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NaamIsVerplicht {
            get {
                return ResourceManager.GetString("NaamIsVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigatie {
            get {
                return ResourceManager.GetString("Navigatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Nee {
            get {
                return ResourceManager.GetString("Nee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New audio sermons.
        /// </summary>
        public static string NieuweAudioPreken {
            get {
                return ResourceManager.GetString("NieuweAudioPreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event.
        /// </summary>
        public static string NieuweGebeurtenis {
            get {
                return ResourceManager.GetString("NieuweGebeurtenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string NieuweGebruiker {
            get {
                return ResourceManager.GetString("NieuweGebruiker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reading Sermons.
        /// </summary>
        public static string NieuweLeespreken {
            get {
                return ResourceManager.GetString("NieuweLeespreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lectures.
        /// </summary>
        public static string NieuweLezingen {
            get {
                return ResourceManager.GetString("NieuweLezingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New minister.
        /// </summary>
        public static string NieuwePredikant {
            get {
                return ResourceManager.GetString("NieuwePredikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sermons.
        /// </summary>
        public static string NieuwePreken {
            get {
                return ResourceManager.GetString("NieuwePreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New serie.
        /// </summary>
        public static string NieuweSerie {
            get {
                return ResourceManager.GetString("NieuweSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New spotlight item.
        /// </summary>
        public static string NieuweSpotlight {
            get {
                return ResourceManager.GetString("NieuweSpotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New testament.
        /// </summary>
        public static string NieuweTestament {
            get {
                return ResourceManager.GetString("NieuweTestament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermonweb articles.
        /// </summary>
        public static string NieuwOpPrekenweb {
            get {
                return ResourceManager.GetString("NieuwOpPrekenweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter subscriptions.
        /// </summary>
        public static string NieuwsbriefAanmeldingen {
            get {
                return ResourceManager.GetString("NieuwsbriefAanmeldingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string NieuwsbriefEmail {
            get {
                return ResourceManager.GetString("NieuwsbriefEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string NieuwsbriefEmailVerplicht {
            get {
                return ResourceManager.GetString("NieuwsbriefEmailVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter subscriptions.
        /// </summary>
        public static string NieuwsbriefInschrijvingen {
            get {
                return ResourceManager.GetString("NieuwsbriefInschrijvingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NieuwsbriefNaamVerplicht {
            get {
                return ResourceManager.GetString("NieuwsbriefNaamVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request new password.
        /// </summary>
        public static string NieuwWachtwoordOpvragen {
            get {
                return ResourceManager.GetString("NieuwWachtwoordOpvragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NiewsbriefNaam {
            get {
                return ResourceManager.GetString("NiewsbriefNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NuInloggen {
            get {
                return ResourceManager.GetString("NuInloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Omschrijving {
            get {
                return ResourceManager.GetString("Omschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Onderwerp {
            get {
                return ResourceManager.GetString("Onderwerp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required.
        /// </summary>
        public static string OnderwerpIsVerplicht {
            get {
                return ResourceManager.GetString("OnderwerpIsVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished sermons.
        /// </summary>
        public static string OngepubliceerdePreken {
            get {
                return ResourceManager.GetString("OngepubliceerdePreken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Onthouden {
            get {
                return ResourceManager.GetString("Onthouden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string Op {
            get {
                return ResourceManager.GetString("Op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved search queries.
        /// </summary>
        public static string OpgeslagenZoekOpdrachten {
            get {
                return ResourceManager.GetString("OpgeslagenZoekOpdrachten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Opmerking {
            get {
                return ResourceManager.GetString("Opmerking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Opslaan {
            get {
                return ResourceManager.GetString("Opslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old testament.
        /// </summary>
        public static string OudeTestament {
            get {
                return ResourceManager.GetString("OudeTestament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information.
        /// </summary>
        public static string OverigeInformatie {
            get {
                return ResourceManager.GetString("OverigeInformatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Paginas {
            get {
                return ResourceManager.GetString("Paginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pauze {
            get {
                return ResourceManager.GetString("Pauze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayerKop {
            get {
                return ResourceManager.GetString("PlayerKop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have an Apple iTunes Podcast which makes offline sermon listening a lot easier. If you like to read more about it click OK.
        /// </summary>
        public static string PodcastMeerInfo {
            get {
                return ResourceManager.GetString("PodcastMeerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister.
        /// </summary>
        public static string Predikant {
            get {
                return ResourceManager.GetString("Predikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministers.
        /// </summary>
        public static string Predikanten {
            get {
                return ResourceManager.GetString("Predikanten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermon.
        /// </summary>
        public static string Preek {
            get {
                return ResourceManager.GetString("Preek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sermon.
        /// </summary>
        public static string PreekMaken {
            get {
                return ResourceManager.GetString("PreekMaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermon saved succesfully, click here to continue editing this sermon.
        /// </summary>
        public static string PreekOpgeslagen {
            get {
                return ResourceManager.GetString("PreekOpgeslagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload sermon.
        /// </summary>
        public static string PreekToevoegen {
            get {
                return ResourceManager.GetString("PreekToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermontype.
        /// </summary>
        public static string PreekType {
            get {
                return ResourceManager.GetString("PreekType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio sermons.
        /// </summary>
        public static string Preken {
            get {
                return ResourceManager.GetString("Preken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons from.
        /// </summary>
        public static string PrekenInBoek {
            get {
                return ResourceManager.GetString("PrekenInBoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons spoken in.
        /// </summary>
        public static string PrekenInTaal {
            get {
                return ResourceManager.GetString("PrekenInTaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons from.
        /// </summary>
        public static string Prekenuit {
            get {
                return ResourceManager.GetString("Prekenuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons in series.
        /// </summary>
        public static string PrekenUitDeSerie {
            get {
                return ResourceManager.GetString("PrekenUitDeSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons from.
        /// </summary>
        public static string PrekenUitGemeente {
            get {
                return ResourceManager.GetString("PrekenUitGemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons of.
        /// </summary>
        public static string PrekenVanPredikant {
            get {
                return ResourceManager.GetString("PrekenVanPredikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermons for.
        /// </summary>
        public static string PrekenVoorGebeurtenis {
            get {
                return ResourceManager.GetString("PrekenVoorGebeurtenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SermonWeb.
        /// </summary>
        public static string PrekenWeb {
            get {
                return ResourceManager.GetString("PrekenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermonweb.org.
        /// </summary>
        public static string PrekenWebNL {
            get {
                return ResourceManager.GetString("PrekenWebNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search sermons.
        /// </summary>
        public static string PrekenZoeken {
            get {
                return ResourceManager.GetString("PrekenZoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 1.
        /// </summary>
        public static string Punt1 {
            get {
                return ResourceManager.GetString("Punt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 2.
        /// </summary>
        public static string Punt2 {
            get {
                return ResourceManager.GetString("Punt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 3.
        /// </summary>
        public static string Punt3 {
            get {
                return ResourceManager.GetString("Punt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 4.
        /// </summary>
        public static string Punt4 {
            get {
                return ResourceManager.GetString("Punt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 5.
        /// </summary>
        public static string Punt5 {
            get {
                return ResourceManager.GetString("Punt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide feedback.
        /// </summary>
        public static string ReactieGeven {
            get {
                return ResourceManager.GetString("ReactieGeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sermon.
        /// </summary>
        public static string ReadingSermon {
            get {
                return ResourceManager.GetString("ReadingSermon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is required, we will not send you email unless you subscribe to our newsletter or when you forgot your password.
        /// </summary>
        public static string RegistreerEmailTooltip {
            get {
                return ResourceManager.GetString("RegistreerEmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will login using this username.
        /// </summary>
        public static string RegistreerGebruikersnaamTooltip {
            get {
                return ResourceManager.GetString("RegistreerGebruikersnaamTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your own account.
        /// </summary>
        public static string RegistreerUwAccount {
            get {
                return ResourceManager.GetString("RegistreerUwAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Registreren {
            get {
                return ResourceManager.GetString("Registreren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Resultaten {
            get {
                return ResourceManager.GetString("Resultaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Rollen {
            get {
                return ResourceManager.GetString("Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First save this search using the button &apos;Save this search&apos; then go to &apos;My SermonWeb&apos; page &apos;Saved search queries&apos; and click on &apos;Rss feed&apos;.
        /// </summary>
        public static string RssFeedZoekIndexLinkAlert {
            get {
                return ResourceManager.GetString("RssFeedZoekIndexLinkAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletters.
        /// </summary>
        public static string SelectedNieuwsbrieven {
            get {
                return ResourceManager.GetString("SelectedNieuwsbrieven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or multiple newsletters to receive, you can select multiple by holding the ctrl button and click.
        /// </summary>
        public static string SelectedNieuwsbrievenTooltip {
            get {
                return ResourceManager.GetString("SelectedNieuwsbrievenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simpel {
            get {
                return ResourceManager.GetString("Simpel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this popup.
        /// </summary>
        public static string SluitDezePopup {
            get {
                return ResourceManager.GetString("SluitDezePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Soort {
            get {
                return ResourceManager.GetString("Soort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SorteerOp {
            get {
                return ResourceManager.GetString("SorteerOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Sortering {
            get {
                return ResourceManager.GetString("Sortering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file.
        /// </summary>
        public static string SourceFileName {
            get {
                return ResourceManager.GetString("SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotlight items.
        /// </summary>
        public static string SpotlightItems {
            get {
                return ResourceManager.GetString("SpotlightItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Stamgegevens {
            get {
                return ResourceManager.GetString("Stamgegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search, listen and read audio and reading sermons from ministers of the &apos;Reformed Congregations&apos;.
        /// </summary>
        public static string StandaardMetaDescription {
            get {
                return ResourceManager.GetString("StandaardMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Taal {
            get {
                return ResourceManager.GetString("Taal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Tekst {
            get {
                return ResourceManager.GetString("Tekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required.
        /// </summary>
        public static string TekstIsVerplicht {
            get {
                return ResourceManager.GetString("TekstIsVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Telefoon {
            get {
                return ResourceManager.GetString("Telefoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Terug {
            get {
                return ResourceManager.GetString("Terug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search results.
        /// </summary>
        public static string TerugNaarZoekresultaten {
            get {
                return ResourceManager.GetString("TerugNaarZoekresultaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Thema {
            get {
                return ResourceManager.GetString("Thema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme &amp; points.
        /// </summary>
        public static string ThemaEnPunten {
            get {
                return ResourceManager.GetString("ThemaEnPunten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Titel {
            get {
                return ResourceManager.GetString("Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of a Bible book, for example: &apos;Matthew&apos;, &apos;Revela&apos; or &apos;Sunday 12&apos;.
        /// </summary>
        public static string TooltipBijbelboek {
            get {
                return ResourceManager.GetString("TooltipBijbelboek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of an event, for example: Holy Supper, Passion, Holy Baptism and similar.
        /// </summary>
        public static string TooltipGebeurtenis {
            get {
                return ResourceManager.GetString("TooltipGebeurtenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your username or email.
        /// </summary>
        public static string TooltipGebruikersnaam {
            get {
                return ResourceManager.GetString("TooltipGebruikersnaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on Bible book chapter.
        /// </summary>
        public static string TooltipHoofdstuk {
            get {
                return ResourceManager.GetString("TooltipHoofdstuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this field to search in a (part of the) ministers lastname.
        /// </summary>
        public static string TooltipPredikant {
            get {
                return ResourceManager.GetString("TooltipPredikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to search thru minister, theme, Bible book, a part of a bibletext. This searchterm can be combined with the other searchfields.
        /// </summary>
        public static string TooltipZoekterm {
            get {
                return ResourceManager.GetString("TooltipZoekterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till.
        /// </summary>
        public static string Tot {
            get {
                return ResourceManager.GetString("Tot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till verse (value from old site).
        /// </summary>
        public static string TotVers {
            get {
                return ResourceManager.GetString("TotVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse till.
        /// </summary>
        public static string TotVersId {
            get {
                return ResourceManager.GetString("TotVersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets are  being loaded.
        /// </summary>
        public static string TweetsWordenGeladen {
            get {
                return ResourceManager.GetString("TweetsWordenGeladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are differnt.
        /// </summary>
        public static string TweeVerschillendeWachtwoord {
            get {
                return ResourceManager.GetString("TweeVerschillendeWachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SermonWeb.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string Uit {
            get {
                return ResourceManager.GetString("Uit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Uitloggen {
            get {
                return ResourceManager.GetString("Uitloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required.
        /// </summary>
        public static string UMoetInloggen {
            get {
                return ResourceManager.GetString("UMoetInloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to use this functionality..
        /// </summary>
        public static string UMoetInloggenToelichting {
            get {
                return ResourceManager.GetString("UMoetInloggenToelichting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a new sermon.
        /// </summary>
        public static string UploadEenNieuwePreek {
            get {
                return ResourceManager.GetString("UploadEenNieuwePreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading and saving in database... Do not close this page!.
        /// </summary>
        public static string UploadenOpslaan {
            get {
                return ResourceManager.GetString("UploadenOpslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Van {
            get {
                return ResourceManager.GetString("Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string Vanaf {
            get {
                return ResourceManager.GetString("Vanaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From verse (value from old site).
        /// </summary>
        public static string VanVers {
            get {
                return ResourceManager.GetString("VanVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse (from).
        /// </summary>
        public static string VanVersId {
            get {
                return ResourceManager.GetString("VanVersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string VeldVerplicht {
            get {
                return ResourceManager.GetString("VeldVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit improvement.
        /// </summary>
        public static string VerbeteringDoorgeven {
            get {
                return ResourceManager.GetString("VerbeteringDoorgeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string VerderZoeken {
            get {
                return ResourceManager.GetString("VerderZoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse.
        /// </summary>
        public static string Vers {
            get {
                return ResourceManager.GetString("Vers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse description.
        /// </summary>
        public static string VersOmschrijving {
            get {
                return ResourceManager.GetString("VersOmschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the textual value of the verses the sermon is about.  This value is displayed in searchresults and the sermon title. For example &apos;1-4&apos; or &apos;3a - Jona 2 : 12&apos;.
        /// </summary>
        public static string VersOmschrijvingTooltip {
            get {
                return ResourceManager.GetString("VersOmschrijvingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the subject of the sermon is about multiple verses, this is the last verse.
        /// </summary>
        public static string VersTotIdTooltip {
            get {
                return ResourceManager.GetString("VersTotIdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Verstuur {
            get {
                return ResourceManager.GetString("Verstuur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting verse on which the sermon is about.
        /// </summary>
        public static string VersVanIdTooltip {
            get {
                return ResourceManager.GetString("VersVanIdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Verwijder {
            get {
                return ResourceManager.GetString("Verwijder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Twitter.
        /// </summary>
        public static string VolgOnsOpTwitter {
            get {
                return ResourceManager.GetString("VolgOnsOpTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string VolledigeNaam {
            get {
                return ResourceManager.GetString("VolledigeNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string Voor {
            get {
                return ResourceManager.GetString("Voor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Wachtwoord {
            get {
                return ResourceManager.GetString("Wachtwoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string WachtwoordAanpassen {
            get {
                return ResourceManager.GetString("WachtwoordAanpassen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype your password.
        /// </summary>
        public static string WachtwoordCheck {
            get {
                return ResourceManager.GetString("WachtwoordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string WachtwoordOpnieuwInstellen {
            get {
                return ResourceManager.GetString("WachtwoordOpnieuwInstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string WachtwoordVergeten {
            get {
                return ResourceManager.GetString("WachtwoordVergeten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SermonWeb.org - Password recovery.
        /// </summary>
        public static string WachtwoordVergetenEmailOnderwerp {
            get {
                return ResourceManager.GetString("WachtwoordVergetenEmailOnderwerp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string WachtwoordVerplicht {
            get {
                return ResourceManager.GetString("WachtwoordVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is My SermonWeb.
        /// </summary>
        public static string WatIsMijnPW {
            get {
                return ResourceManager.GetString("WatIsMijnPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show welcome text.
        /// </summary>
        public static string WelkomstTekstTonen {
            get {
                return ResourceManager.GetString("WelkomstTekstTonen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this text.
        /// </summary>
        public static string WelkomstTekstVerbergen {
            get {
                return ResourceManager.GetString("WelkomstTekstVerbergen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string Wis {
            get {
                return ResourceManager.GetString("Wis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string WisFilters {
            get {
                return ResourceManager.GetString("WisFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing.
        /// </summary>
        public static string Zingen {
            get {
                return ResourceManager.GetString("Zingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Zoek {
            get {
                return ResourceManager.GetString("Zoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a searchterm, for example: minister, theme, Bible book or a part of a bible text.
        /// </summary>
        public static string ZoekboxStandaardTekst {
            get {
                return ResourceManager.GetString("ZoekboxStandaardTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Zoeken {
            get {
                return ResourceManager.GetString("Zoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string ZoekenBoek {
            get {
                return ResourceManager.GetString("ZoekenBoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ZoekenGebeurtenis {
            get {
                return ResourceManager.GetString("ZoekenGebeurtenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congregations.
        /// </summary>
        public static string ZoekenGemeente {
            get {
                return ResourceManager.GetString("ZoekenGemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ministers.
        /// </summary>
        public static string ZoekenPredikant {
            get {
                return ResourceManager.GetString("ZoekenPredikant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string ZoekenSerie {
            get {
                return ResourceManager.GetString("ZoekenSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this search.
        /// </summary>
        public static string ZoekOpdrachtBewaren {
            get {
                return ResourceManager.GetString("ZoekOpdrachtBewaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Zoekresultaten {
            get {
                return ResourceManager.GetString("Zoekresultaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchterm.
        /// </summary>
        public static string Zoekterm {
            get {
                return ResourceManager.GetString("Zoekterm", resourceCulture);
            }
        }
    }
}
